[package]
name = "oidc-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oidc-server = { path = "../server" }
oidc-core = { path = "../core" }
oidc-types = { path = "../types" }
oidc-admin = { path = "../admin" }
axum = { version = "0.6.15", features = ["form"] }
hyper = { version = "0.14.26", features = ["full"] }
tokio = { version = "1.27.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["fs"] }
tera = "1.18.1"
time = "0.3.20"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde="1.0.160"
serde_json = "1.0.96"
lazy_static = "1.4.0"
urlencoding="2.1.2"

[dev-dependencies]
axum-macros = "0.3.7"
