[package]
name = "oidc-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oidc-server = { path = "../server" }
oidc-core = { path = "../core" }
oidc-types = { path = "../types" }
axum = "0.5.12"
hyper = { version = "0.14.20", features = ["full"] }
tokio = { version = "1.20.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["fs"] }
env_logger = "0.9.0"
tera = "1.16.0"
rand = "0.8.5"
time = "0.3.11"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
