[package]
name = "oidc-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oidc-server = { path = "../server" }
oidc-core = { path = "../core" }
oidc-types = { path = "../types" }
oidc-admin = { path = "../admin" }
axum = { version = "0.5.16", features = ["form"] }
hyper = { version = "0.14.20", features = ["full"] }
tokio = { version = "1.21.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["fs"] }
tera = "1.16.0"
time = "0.3.11"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
serde="1.0.139"
serde_json = "1.0.85"
lazy_static = "1.4.0"
urlencoding="2.1.2"

[dev-dependencies]
axum-macros = "0.2.3"
