name: rust-oidc-provider

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oidc-provider
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - db:/var/lib/mysql

volumes:
  db: