//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "interaction_type")]
pub enum InteractionType {
    #[sea_orm(string_value = "Login")]
    Login,
    #[sea_orm(string_value = "Consent")]
    Consent,
    #[sea_orm(string_value = "None")]
    None,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "Awaiting")]
    Awaiting,
    #[sea_orm(string_value = "Consumed")]
    Consumed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "token_type")]
pub enum TokenType {
    #[sea_orm(string_value = "Access")]
    Access,
    #[sea_orm(string_value = "Refresh")]
    Refresh,
}
