//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use super::sea_orm_active_enums::Status;
use super::sea_orm_active_enums::TokenType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Binary(BlobSize::Blob(Some(16)))"
    )]
    pub token: Vec<u8>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(Some(16)))")]
    pub grant_id: Vec<u8>,
    pub status: Status,
    pub token_type: TokenType,
    pub expires_in: TimeDateTimeWithTimeZone,
    pub created: TimeDateTimeWithTimeZone,
    pub scopes: String,
    pub t_type: Option<String>,
    pub state: Option<String>,
    pub nonce: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::grant::Entity",
        from = "Column::GrantId",
        to = "super::grant::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Grant,
}

impl Related<super::grant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
